export const IE_ADDRESS = "0x1e4FE500980000D7679EcE0000D000B49E740493";
export const IE_ABI = [
  { inputs: [], stateMutability: "payable", type: "constructor" },
  { inputs: [], name: "InsufficientSwap", type: "error" },
  { inputs: [], name: "InvalidCharacter", type: "error" },
  { inputs: [], name: "InvalidReceiver", type: "error" },
  { inputs: [], name: "InvalidSelector", type: "error" },
  { inputs: [], name: "InvalidSwap", type: "error" },
  { inputs: [], name: "InvalidSyntax", type: "error" },
  { inputs: [], name: "OrderExpired", type: "error" },
  { inputs: [], name: "Overflow", type: "error" },
  { inputs: [], name: "Reentrancy", type: "error" },
  { inputs: [], name: "Unauthorized", type: "error" },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "token",
        type: "address",
      },
      { indexed: false, internalType: "string", name: "name", type: "string" },
    ],
    name: "NameSet",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "token0",
        type: "address",
      },
      {
        indexed: false,
        internalType: "address",
        name: "token1",
        type: "address",
      },
      {
        indexed: false,
        internalType: "address",
        name: "pair",
        type: "address",
      },
    ],
    name: "PairSet",
    type: "event",
  },
  { stateMutability: "payable", type: "fallback" },
  {
    inputs: [{ internalType: "string", name: "name", type: "string" }],
    name: "addresses",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "bytes32", name: "hash", type: "bytes32" }],
    name: "cancelOrder",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "string", name: "intent", type: "string" },
      {
        components: [
          { internalType: "address", name: "sender", type: "address" },
          { internalType: "uint256", name: "nonce", type: "uint256" },
          { internalType: "bytes", name: "initCode", type: "bytes" },
          { internalType: "bytes", name: "callData", type: "bytes" },
          {
            internalType: "bytes32",
            name: "accountGasLimits",
            type: "bytes32",
          },
          {
            internalType: "uint256",
            name: "preVerificationGas",
            type: "uint256",
          },
          { internalType: "bytes32", name: "gasFees", type: "bytes32" },
          { internalType: "bytes", name: "paymasterAndData", type: "bytes" },
          { internalType: "bytes", name: "signature", type: "bytes" },
        ],
        internalType: "struct IEBase.PackedUserOperation",
        name: "userOp",
        type: "tuple",
      },
    ],
    name: "checkUserOp",
    outputs: [{ internalType: "bool", name: "intentMatched", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "string[]", name: "intents", type: "string[]" }],
    name: "command",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [{ internalType: "string", name: "intent", type: "string" }],
    name: "command",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "string", name: "to", type: "string" },
      { internalType: "string", name: "amount", type: "string" },
      { internalType: "string", name: "token", type: "string" },
      { internalType: "string", name: "time", type: "string" },
      { internalType: "string", name: "unit", type: "string" },
    ],
    name: "escrow",
    outputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [{ internalType: "bytes32", name: "hash", type: "bytes32" }],
    name: "executeOrder",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "string", name: "to", type: "string" },
      { internalType: "string", name: "amount", type: "string" },
      { internalType: "string", name: "token", type: "string" },
      { internalType: "string", name: "time", type: "string" },
      { internalType: "string", name: "unit", type: "string" },
    ],
    name: "lock",
    outputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "addresses", type: "address" }],
    name: "names",
    outputs: [{ internalType: "string", name: "", type: "string" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "string", name: "tokenIn", type: "string" },
      { internalType: "string", name: "tokenOut", type: "string" },
      { internalType: "string", name: "amountIn", type: "string" },
      { internalType: "string", name: "amountOut", type: "string" },
      { internalType: "string", name: "receiver", type: "string" },
    ],
    name: "order",
    outputs: [{ internalType: "bytes32", name: "hash", type: "bytes32" }],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    name: "orderHashes",
    outputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "bytes32", name: "orderHash", type: "bytes32" }],
    name: "orders",
    outputs: [
      { internalType: "address", name: "tokenIn", type: "address" },
      { internalType: "address", name: "tokenOut", type: "address" },
      { internalType: "uint256", name: "amountIn", type: "uint256" },
      { internalType: "uint256", name: "amountOut", type: "uint256" },
      { internalType: "address", name: "maker", type: "address" },
      { internalType: "address", name: "receiver", type: "address" },
      { internalType: "uint48", name: "nonce", type: "uint48" },
      { internalType: "uint48", name: "expiry", type: "uint48" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "token0", type: "address" },
      { internalType: "address", name: "token1", type: "address" },
    ],
    name: "pairs",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "string", name: "intent", type: "string" }],
    name: "previewCommand",
    outputs: [
      { internalType: "address", name: "to", type: "address" },
      { internalType: "uint256", name: "amount", type: "uint256" },
      { internalType: "uint256", name: "minAmountOut", type: "uint256" },
      { internalType: "address", name: "token", type: "address" },
      { internalType: "bytes", name: "callData", type: "bytes" },
      { internalType: "bytes", name: "executeCallData", type: "bytes" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "string", name: "to", type: "string" },
      { internalType: "string", name: "amount", type: "string" },
      { internalType: "string", name: "token", type: "string" },
    ],
    name: "send",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "token", type: "address" },
      { internalType: "string", name: "name", type: "string" },
    ],
    name: "setName",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "tokenA", type: "address" },
      { internalType: "address", name: "tokenB", type: "address" },
      { internalType: "address", name: "pair", type: "address" },
    ],
    name: "setPair",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "string", name: "amountIn", type: "string" },
      { internalType: "string", name: "amountOutMin", type: "string" },
      { internalType: "string", name: "tokenIn", type: "string" },
      { internalType: "string", name: "tokenOut", type: "string" },
      { internalType: "string", name: "receiver", type: "string" },
    ],
    name: "swap",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [{ internalType: "bytes", name: "callData", type: "bytes" }],
    name: "translateCommand",
    outputs: [{ internalType: "string", name: "intent", type: "string" }],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [{ internalType: "bytes", name: "callData", type: "bytes" }],
    name: "translateExecute",
    outputs: [{ internalType: "string", name: "intent", type: "string" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        components: [
          { internalType: "address", name: "sender", type: "address" },
          { internalType: "uint256", name: "nonce", type: "uint256" },
          { internalType: "bytes", name: "initCode", type: "bytes" },
          { internalType: "bytes", name: "callData", type: "bytes" },
          {
            internalType: "bytes32",
            name: "accountGasLimits",
            type: "bytes32",
          },
          {
            internalType: "uint256",
            name: "preVerificationGas",
            type: "uint256",
          },
          { internalType: "bytes32", name: "gasFees", type: "bytes32" },
          { internalType: "bytes", name: "paymasterAndData", type: "bytes" },
          { internalType: "bytes", name: "signature", type: "bytes" },
        ],
        internalType: "struct IEBase.PackedUserOperation",
        name: "userOp",
        type: "tuple",
      },
    ],
    name: "translateUserOp",
    outputs: [{ internalType: "string", name: "intent", type: "string" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "string", name: "name", type: "string" }],
    name: "whatIsTheAddressOf",
    outputs: [
      { internalType: "address", name: "owner", type: "address" },
      { internalType: "address", name: "receiver", type: "address" },
      { internalType: "bytes32", name: "node", type: "bytes32" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "user", type: "address" }],
    name: "whatIsTheNameOf",
    outputs: [{ internalType: "string", name: "", type: "string" }],
    stateMutability: "view",
    type: "function",
  },
  { stateMutability: "payable", type: "receive" },
] as const;
